Updated Extend section in Readme
jacalata/pseudoloc pull request #2
Opened 2018-02-28 13:25 UTC by Johnken-S

Hi @jacalata 
Here goes the PR for Readme.  Also, When will be new release in 
https://www.npmjs.com/package/pseudoloc-js ?
Noticed that in Keywords : Pseudoloc' is wrongly spelt as 'psuedoloc'.

John

2018-02-28 19:01 UTC, MickMonaghan commented on Readme.md
> +We extend it by a set of predefined Asian characters.
They're not all Asian characters. How about:
`We extend the string by randomly selecting characters from a predefined array of non-ASCII characters`

2018-02-28 19:05 UTC, MickMonaghan commented on Readme.md
> +New update: Extends the width of the string by the specified percentage will be filled with Asian characters including emoji.
The emoji character is not necessarily part of the extended string - they're randomly chosen from the array declared in the `pad` function.

2018-03-01 01:11 UTC, jacalata requested changes
I think Mick's suggestions are good, can you include them? I'll update the npm package once this readme is in.

2018-03-01 07:25 UTC, Johnken-S commented
@jacalata  I have now updated based on @MickMonaghan  suggesstions.

2018-03-01 15:55 UTC, MickMonaghan commented
Do we also need to replace instances of `pseudoloc` with `pseudoloc-js`? - such as in the `require` statement etc.?

2018-03-01 20:58 UTC, jacalata approved these changes

2018-03-01 20:58 UTC, merged

2018-03-01 21:00 UTC, jacalata commented
I don't think there's any updates required for that, the package name is pseudoloc-js but the filename that require looks for is still just pseudoloc.  But I haven't run that example code recently - was it not working somwhere?

2018-03-01 21:23 UTC, MickMonaghan commented
Ah, ok. Not an issue then. Thanks.

2018-03-11 16:15 UTC, Johnken-S commented
Hi @jacalata : 
Can you please update the npm pseudoloc-js package with latest code changes?
Thank you!

2018-03-11 22:21 UTC, jacalata commented
done, sorry for the delay! Also fixed a test that had been broken by the double-encoding padded chars (because javascript is so lame at string length)

2018-03-12 08:11 UTC, Johnken-S commented
Thank you, @jacalata .